config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'static_pages#home'

  resources :clients do
    resources :matches, only: [:show, :index]
  end

  resources :volunteers do
    resources :matches, only: [:show, :index]
    member do
      post 'add_availabilities'
      patch 'add_specialty'
      get 'remove_specialty'
    end
  end

  get 'matches/explorer' => 'matches#explorer', as: :matches_explorer
  resources :match_explorations, only: 'create'
  resources :matches
  resources :match_requests, only: [:update]
  resources :match_proposals do
    resources :match_requests
  end
  resources :availabilities
  resources :specialties
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_many :matches, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  has_and_belongs_to_many :specialties

  validates :first_name, presence: true
  validates :last_name, presence: true

  geocoded_by :full_address
  after_validation :geocode,
                   if: ->(volunteer) { volunteer.any_address_changed? }

  def name
    "#{first_name} #{last_name}"
  end

  def full_address
    return unless has_address?
    "#{address}, #{city} #{province}, #{postal_code}"
  end

  def available?(match_time)
    matching_availabilities = load_matching_availabilities(match_time)

    matching_availabilities && matching_availabilities.size > 0
  end

  def load_matching_availabilities(match_time)
    availabilities.select do |availability|
      availability_matching?(availability, match_time)
    end
  end

  def any_address_changed?
    address_changed? || city_changed? || province_changed? || postal_code_changed?
  end

  def has_been_geocoded?
    !latitude.nil? && !longitude.nil?
  end

  def merge_volunteer_availabilities
    service = AvailabilityMergingService.new(self)
    service.merge
    service.flash_message
  end

  private

  def availability_matching?(availability, match_time)
    availability.time_range.contains(match_time)
  end

  def has_address?
    !address.nil? && address.size > 0
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  include BreadcrumbGenerator

  def create
    @volunteer = Volunteer.new(volunteer_params)
    if @volunteer.save
      redirect_to @volunteer
    else
      flash.now[:error] = @volunteer.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    load_assigns(:volunteer, :availabilities, :specialties)
    @matches = @volunteer.matches
    @specialties_options = Specialty.all
    @load_map_js = true
    load_breadcrumbs(crumb_class: Volunteer, crumb_instance: @volunteer)
  end

  def edit(_flash_message = nil)
    load_volunteer
    load_breadcrumbs(crumb_class: Volunteer, crumb_instance: @volunteer, crumb_actions: [:edit])
  end

  def new
    @volunteer = Volunteer.new
    load_breadcrumbs(crumb_class: Volunteer, crumb_actions: [:new])
  end

  def index
    load_volunteers
    load_breadcrumbs(crumb_class: Volunteer)
  end

  def destroy
    load_volunteer
    @volunteer.destroy
    redirect_to volunteers_path
  end

  def update
    load_volunteer

    if @volunteer.update(volunteer_params)
      redirect_to @volunteer
    else
      flash.now[:error] = @volunteer.errors.full_messages.to_sentence
      load_availabilities
      redirect_to 'edit'
    end
  end

  def add_specialty
    load_volunteer

    service = SpecialtyService.new(specialty_params)
    service.add_specialty_to_volunteer

    flash[:error] = service.flash_message
    redirect_to @volunteer
  end

  def remove_specialty
    load_volunteer
    service = SpecialtyService.new(specialty_params)
    service.remove_specialty_from_volunteer

    redirect_to @volunteer
  end

  def add_availabilities
    service = AvailabilityService.new(availability_service_params)
    service.new_availability(availability_params)

    flash[:error] = service.availability_errors
    flash[:notice] = service.merging_result
    load_assigns(:volunteer, :availabities)
    load_availabilities

    @specialties_options = Specialty.all
    redirect_to @volunteer
  end

  private

  def load_assigns(*assigns)
    assigns.map!(&:to_sym)

    load_volunteer if assigns.include?(:volunteer)
    load_volunteers if assigns.include?(:volunteers)
    load_availabilities if assigns.include?(:availabilities)
    load_specialties if assigns.include?(:specialties)
  end

  def load_volunteer
    @volunteer = Volunteer.find(params[:id])
  end

  def load_volunteers
    @volunteers = Volunteer.all.order(last_name: :asc).includes(:matches)
  end

  def load_availabilities
    service = AvailabilityService.new(availability_service_params)
    @availability = service.availability
    @availabilities = service.availabilities
  end

  def load_specialties
    @specialties = @volunteer.specialties.order(name: :asc)
  end

  def availability_params
    params.require(:availability).permit(:start_time, :end_time, :day)
  end

  def availability_service_params
    params.permit(:id)
  end

  def volunteer_params
    params.require(:volunteer).permit(:last_name, :first_name, :specialty_ids, :address, :city, :province, :postal_code)
  end

  def specialty_params
    params.permit(:id, volunteer: [:specialty_ids])
  end
end

app/views/volunteers/_form.html.erb
<%= form_for @volunteer do |f| %>
    <div class="width50">
      <%= label_tag(:first_name, "First Name") %>
      <%= f.text_field :first_name, class: 'form_field' %>
    </div>
    <div class="width50">
      <%= label_tag(:last_name, "Last Name") %>
      <%= f.text_field :last_name, class: 'form_field' %>
    </div>
    <div class="width50">
      <%= label_tag(:address, "Address") %>
      <%= f.text_field :address, class: 'form_field' %>
    </div>
    <div class="width50">
      <%= label_tag(:city, "City") %>
      <%= f.text_field :city, class: 'form_field' %>
    </div>
    <div class="width50">
      <%= label_tag(:province, "Province") %>
      <%= f.text_field :province, class: 'form_field' %>
    </div>
    <div class="width50">
      <%= label_tag(:postal_code, "Postal Code") %>
      <%= f.text_field :postal_code, class: 'form_field' %>
    </div>
    <%= f.submit "Submit" %>
<% end %>

app/views/volunteers/_table.html.erb
<table>
  <th>Name</th>
  <th>Number of matches</th>
  <th>Actions</th>

  <% @volunteers.each do |volunteer| %>
      <tr>
        <td>
          <%= link_to volunteer.name, volunteer %>
        </td>
        <td>
          <%= volunteer.matches.size %>
        </td>
        <td><%= link_to "Edit", edit_volunteer_path(volunteer.id) %></td>
      </tr>

  <% end %>
</table>

app/views/volunteers/edit.html.erb
<%= link_to 'Delete this volunteer', volunteer_path(@volunteer), class: [:button, 'float_right'], method: :delete, data: { confirm: 'Are you sure?' } %>
<h1>Edit volunteer: <%= @volunteer.name %></h1>
<%= render "form" %>

app/views/volunteers/index.html.erb
<%= link_to 'New volunteer', new_volunteer_path, class: [:button, 'float_right'] %>
<h1>Volunteers</h1>
<%= render "table" %>

app/views/volunteers/new.html.erb
<h1>Add a volunteer</h1>
<%= render "form" %>

app/views/volunteers/show.html.erb
<%= link_to 'Edit volunteer', edit_volunteer_path(@volunteer), class: [:button, 'float_right'] %>
<h1>Volunteer: <%= @volunteer.first_name %> <%= @volunteer.last_name %></h1>

<table class="meta_table">
  <tr>
    <th>ID</th>
    <td>
      <%= @volunteer.id %>
    </td>
  </tr>
  <tr>
    <th>First name</th>
    <td>
      <%= @volunteer.first_name %>
    </td>
  </tr>
  <tr>
    <th>Last name</th>
    <td>
      <%= @volunteer.last_name %>
    </td>
  </tr>
  <tr>
    <th>Address</th>
    <td>
      <%= @volunteer.full_address %>
    </td>
  </tr>
  <tr>
    <th>Date created</th>
    <td>
      <%= formatted_created_at(@volunteer) %>
    </td>
  </tr>
</table>

<h2>Specialties</h2>

<% if @specialties && @specialties.size > 0 %>
    <% @specialties.each do |specialty| %>
        <span class="badge badge-notice specialty"><%= link_to specialty.name, specialty %>
          <%= link_to fa_icon('close'), {
                                          controller: 'volunteers',
                                          action: 'remove_specialty',
                                          volunteer: {
                                            specialty_ids: specialty.id
                                          }
                                        },
                                        class: 'red remove_specialty' %>
        </span>
    <% end %>
<% else %>
    <p><%= @volunteer.name %> has no specialties.</p>
<% end %>

<%= form_for @volunteer, url: {action: 'add_specialty'}, html: {class: :horizontal_form} do |f| %>
    <div class="label">
      <%= label_tag(:specialty, "Add specialty:") %>
    </div>
    <div class="input stretch">
      <%= f.select :specialty_ids,
                   @specialties_options.collect { |specialty_option| [specialty_option.name, specialty_option.id] },
                   selected: @specialties_options.first,
                   class: 'form_field',
                   id: 'specialty_ids'
      %>
    </div>
    <div class="button_container">
      <%= f.submit "Add", id: 'add_specialty' %>
    </div>
<% end %>


<h2>Availability</h2>
<table id="availability_table">
  <tr>
    <th>Day</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Actions</th>
  </tr>
  <% @availabilities.each do |availability| %>
      <tr>
        <td class="availability_table_day"><%= availability.day.capitalize %></td>
        <td class="availability_table_start_time"><%= availability.start_time %></td>
        <td class="availability_table_end_time"><%= availability.end_time %></td>
        <td class="availability_actions">
          <%= link_to 'Edit', edit_availability_path(availability) %>,
          <%= link_to 'Delete', availability_path(availability),
                      method: :delete
          %>
        </td>
      </tr>
  <% end %>
</table>

<%= form_for @availability, url: add_availabilities_volunteer_path(@volunteer), html: {class: :horizontal_form} do |f| %>
    <div class="label">
      <%= label_tag(:day, "Add availability:") %>
    </div>
    <div class="input" style="width: 50%;">
      <%= f.select :day, DAY_OPTIONS, class: 'form_field' %>
    </div>
    <div class="label">
      <%= label_tag(:start_time, "from:") %>
    </div>
    <div class="input">
      <%= f.text_field :start_time, class: 'form_field', type: 'number', min: 0, max: 23 %>
    </div>
    <div class="label">
      <%= label_tag(:end_time, "to:") %>
    </div>
    <div class="input">
      <%= f.text_field :end_time, class: 'form_field', type: 'number', min: 1, max: 24 %>
    </div>
    <div class="button_container">
      <%= f.submit "Add", id: 'add_availability' %>
    </div>
<% end %>

<h2>Matches</h2>
<% if @matches.size > 0 %>
    <%= render "matches/matches_table", object: @volunteer %>
<% else %>
    <p><%= @volunteer.name %> has no matches.</p>
<% end %>
<%= link_to 'Add match',
            {controller: 'matches',
             action: 'new',
             volunteer_id: @volunteer.id}, class: [:button, 'float_right', 'bottom_margin'], id: 'add_match' %>

<%= render partial: "shared/map", locals: {map_subject: @volunteer} %>