config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'static_pages#home'

  resources :clients do
    resources :matches, only: [:show, :index]
  end

  resources :volunteers do
    resources :matches, only: [:show, :index]
    member do
      post 'add_availabilities'
      patch 'add_specialty'
      get 'remove_specialty'
    end
  end

  get 'matches/explorer' => 'matches#explorer', as: :matches_explorer
  resources :match_explorations, only: 'create'
  resources :matches
  resources :match_requests, only: [:update]
  resources :match_proposals do
    resources :match_requests
  end
  resources :availabilities
  resources :specialties
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% content_for :hero do %>
  <div class="hero">
    <div class="hero-inner">
      <div href="" class="hero-logo">
        <%= image_tag("logo.png") %></div>
      <div class="hero-copy">
        <h1>Hospice at Home</h1>

        <p>Providing care, comfort, and dignity.</p>
      </div>
    </div>
  </div>
<% end %>

<div class="quick-links">
  <%= link_to "#{fa_icon("user", class: 'icon')} New client".html_safe, new_client_path, class: 'button quick-link' %>
  <%= link_to "#{fa_icon("user-md", class: 'icon')} New volunteer".html_safe, new_volunteer_path, class: 'button quick-link' %>
  <%= link_to "#{fa_icon("mortar-board", class: 'icon')} New specialty".html_safe, new_specialty_path, class: 'button quick-link' %>
  <%= link_to "#{fa_icon("calendar", class: 'icon')} New match".html_safe, new_match_path, class: 'button quick-link' %>
  <%= link_to "#{fa_icon("search", class: 'icon')} Match explorer".html_safe, matches_explorer_path, class: 'button quick-link' %>
</div>
<small class="photo-credit">Photo: <a href="https://www.flickr.com/photos/ncvophotos/8591440981/">NCVO London</a>
</small>


<% content_for :inline_css do %>
  <style>
    .breadcrumb {
      display: none;
    }
  </style>
<% end %>