config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'static_pages#home'

  resources :clients do
    resources :matches, only: [:show, :index]
  end

  resources :volunteers do
    resources :matches, only: [:show, :index]
    member do
      post 'add_availabilities'
      patch 'add_specialty'
      get 'remove_specialty'
    end
  end

  get 'matches/explorer' => 'matches#explorer', as: :matches_explorer
  resources :match_explorations, only: 'create'
  resources :matches
  resources :match_requests, only: [:update]
  resources :match_proposals do
    resources :match_requests
  end
  resources :availabilities
  resources :specialties
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :client
  belongs_to :volunteer
  belongs_to :match_request

  DAYS_OF_THE_WEEK = %w(monday tuesday wednesday thursday friday saturday sunday)

  validates :client_id, presence: true
  validates :volunteer_id, presence: true
  validates :start_time, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }
  validates :end_time, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }
  validates_numericality_of :end_time,
                            message: 'must be after start time',
                            greater_than: ->(mp) { mp.start_time },
                            if: ->(mp) { mp.start_time.present? }
  validate :day_is_real_day

  delegate :name, to: :client, prefix: true
  delegate :name, to: :volunteer, prefix: true

  composed_of :match_time, class_name: 'TimeRange', mapping: [
    %w(day day), %w(start_time start_time), %w(end_time end_time)
  ]

  def day_and_time
    "#{day.capitalize}, #{start_time} to #{end_time}"
  end

  def name
    "#{client.name} and #{volunteer.name}"
  end

  private

  def day_is_real_day
    errors.add(:day, 'must be a day of the week') unless DAYS_OF_THE_WEEK.include?(day)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include BreadcrumbGenerator

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to @match
    else
      flash.now[:error] = @match.errors.full_messages.to_sentence
      render_after_create(params[:from_match_explorer])
    end
  end

  def show
    service = MatchLoadingService.new(params, load_collection: false)
    @match = service.match
    @match_proposal = service.match_proposal
    load_breadcrumbs(crumb_class: Match, crumb_instance: @match)
  end

  def edit
    service = MatchLoadingService.new(params, load_collection: false)
    @match = service.match
    load_breadcrumbs(crumb_class: Match, crumb_instance: @match, crumb_actions: [:edit])
  end

  def new
    @volunteer = Volunteer.find(params[:volunteer_id]) if params[:volunteer_id]
    load_new_match
    load_breadcrumbs(crumb_class: Match, crumb_actions: [:new])
  end

  def explorer
    load_new_match
    @match_exploration_params = params[:match_exploration]
    service = MatchExplorerService.new(@match_exploration_params)
    @match_exploration = service.match_exploration
    @match_proposal = MatchProposal.new
    @volunteers = service.volunteers
    @specialty_selected_value = @match_exploration.specialty_id if @match_exploration
    load_breadcrumbs(crumb_class: Match, crumb_actions: [:match_explorer])
  end

  def index
    service = MatchLoadingService.new(params, load_collection: true)
    @matches = service.matches
    @match_proposals = service.match_proposals
    @no_turbolinks = true
    @initial_tab = params[:initial_tab]
    load_breadcrumbs(crumb_class: Match)
    respond_to do |format|
      format.html
      format.json { render json: @matches }
    end
  end

  def destroy
    service = MatchLoadingService.new(params, load_collection: false)
    @match = service.match
    @match.destroy
    redirect_to matches_path
  end

  def update
    service = MatchLoadingService.new(params, load_collection: false)
    @match = service.match
    if @match.update(match_params)
      redirect_to @match
    else
      render 'edit'
    end
  end

  private

  def load_new_match
    @match = Match.new
  end

  def match_params
    params.require(:match).permit(
      :client_id, :volunteer_id, :day, :start_time, :end_time, :from_match_explorer, :initial_tab,
      match_exploration_attributes: [:client_id,
                                     :volunteer_id,
                                     :day,
                                     :start_time,
                                     :end_time,
                                     :specialty_id]
    )
  end

  def render_after_create(from_match_explorer)
    render from_match_explorer ? matches_explorer_path : new_match_path
  end
end

app/views/matches/_form.html.erb
<%= form_for @match do |f| %>
    <div class="width50">
      <%= label_tag(:client_association, "Client") %><br>
      <%= f.collection_select(:client_id, Client.all, :id, :name, prompt: true) %>
    </div>
    <div class="width50">
      <%= label_tag(:volunteer_association, "Volunteer") %><br>
      <% if @volunteer %>
          <%= f.collection_select(:volunteer_id, Volunteer.all, :id, :name, selected: @volunteer.id, prompt: true) %>
      <% else %>
          <%= f.collection_select(:volunteer_id, Volunteer.all, :id, :name, prompt: true) %>
      <% end %>
    </div>

    <div class="width33">
      <%= label_tag(:day, "Day") %>
      <%= f.select(:day, DAY_OPTIONS, class: 'form_field') %>
    </div>
    <div class="width33">
      <%= label_tag(:start_time, "Start time") %>
      <%= f.text_field(:start_time, class: 'form_field', type: 'number', min: 0, max: 23) %>
    </div>
    <div class="width33">
      <%= label_tag(:end_time, "End time") %>
      <%= f.text_field(:end_time, class: 'form_field', type: 'number', min: 1, max: 24) %>
    </div>
    <div style="clear:both;">
      <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/matches/_match_exploration_results.html.erb
<%= form_tag('/match_proposals', method: "post") do %>
    <%= hidden_field_tag(:start_time, @match_exploration_params[:start_time]) %>
    <%= hidden_field_tag(:end_time, @match_exploration_params[:end_time]) %>
    <%= hidden_field_tag(:day, @match_exploration_params[:day]) %>
    <%= hidden_field_tag(:client_id, @match_exploration_params[:client_id]) %>

    <h2>Search results for <%= @match_exploration.day.capitalize %>,
      from <%= @match_exploration.start_time %>
      to <%= @match_exploration.end_time %></h2>
    <% if @volunteers && @volunteers.size > 0 %>
        <%= render "volunteers_table" %>
        <h2>Create a match proposal</h2>

        <p>For a match for <%= @match_exploration_params[:day].capitalize %>
          from <%= @match_exploration_params[:start_time] %>
          to <%= @match_exploration_params[:end_time] %>, with
          client <%= Client.find(@match_exploration_params[:client_id]).name %>.</p>
        <%= submit_tag "Create proposal" %>
    <% else %>
        No volunteers match your search criteria.
    <% end %>

<% end %>

app/views/matches/_matches_table.html.erb
<table>
  <tr>
    <th>Day and time</th>
    <th>Client</th>
    <th>Volunteer</th>
  </tr>
  <% @matches.each do |match| %>
      <tr>
        <td>
          <%= link_to match.day_and_time, [@client, @volunteer, match] %>
        </td>
        <td><%= match.client.name %></td>
        <td><%= match.volunteer.name %></td>
      </tr>
  <% end %>
</table>

app/views/matches/edit.html.erb
<%= link_to 'Delete this match', match_path(@match), class: [:button, 'float_right'], method: :delete, data: { confirm: 'Are you sure?' } %>
<h1>Edit match</h1>
<%= render "form" %>

app/views/matches/explorer.html.erb
<h1>Match Explorer</h1>
<%= render "matches/explorer/match_exploration_form" %>
<% if @match_exploration && !@match_exploration.values_nil? %>
    <% if @match_exploration.valid? %>
        <hr>
        <%= render "matches/explorer/match_exploration_results" %>
    <% else %>
        <div class="MatchExplorer_flash">
          <%= render :partial => "/layouts/flash", :locals => {:flash => {error: @match_exploration.errors.full_messages.to_sentence}} %>
        </div>
    <% end %>
<% end %>

app/views/matches/index.html.erb
<%= link_to 'New match', new_match_path, class: [:button, 'float_right'] %>
<h1>Matches</h1>
<div>
  <ul class="accordion-tabs">
    <li class="tab-header-and-content">
      <a href="javascript:void(0)" class="
      <% if @initial_tab != 'match_proposal' %>is-active
      <% end %> tab-link">Matches</a>

      <div class="tab-content" ng-controller="MatchCtrl">
        <table id="matches_table">
          <tr>
            <th>Day and time <a ng-click="setOrder('date')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
            <th>Client <a ng-click="setOrder('client')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
            <th>Volunteer <a ng-click="setOrder('volunteer')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
          </tr>
          <tr ng-repeat="match in matches | orderBy: orderProp : orderAscending ">
            <td class="matches_table_day_and_time">
              <a href="/matches/{{match.id}}" class="thumb">
                {{ {day: match.day, start_time: match.start_time,
                end_time: match.end_time } | fullDate | capitalize }}
              </a>
            </td>
            <td class="matches_table_client">
              {{match.client.first_name}} {{match.client.last_name}}
            </td>
            <td class="matches_table_volunteer">
              {{match.volunteer.first_name}} {{match.volunteer.last_name}}
            </td>
          </tr>
        </table>
      </div>
    </li>
    <li class="tab-header-and-content">
      <a href="javascript:void(0)" class="
      <% if @initial_tab == 'match_proposal' %>is-active
      <% end %> tab-link">Match proposals</a>

      <div class="tab-content" ng-controller="MatchProposalCtrl">
        <table id="match_proposals_table">
          <tr>
            <th>Day and time <a ng-click="setOrder('date')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
            <th>Client <a ng-click="setOrder('client')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
            <th>Status <a ng-click="setOrder('status')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
            <th>Volunteer requests
              <a ng-click="setOrder('match_requests_size')"><%= fa_icon("sort", class: 'sort_icon') %></a></th>
            <th>Proposal created <a ng-click="setOrder('proposal_date')"><%= fa_icon("sort", class: 'sort_icon') %></a>
            </th>
          </tr>
          <tr ng-repeat="matchProposal in matchProposals | orderBy: orderProp : orderAscending ">
            <td class="match_proposals_table_day_and_time">
              <a href="/match_proposals/{{matchProposal.id}}" class="thumb">
                {{ {day: matchProposal.day, start_time: matchProposal.start_time,
                end_time: matchProposal.end_time } | fullDate | capitalize }}
              </a>
            </td>
            <td class="match_proposals_table_client">
              {{matchProposal.client.first_name}} {{matchProposal.client.last_name}}
            </td>
            <td class="match_proposals_table_status">
              {{matchProposal.status | capitalize}}
            </td>
            <td class="match_proposals_table_requests">
              {{matchProposal.match_requests.length}}
            </td>
            <td class="match_proposals_table_date_created">
              {{matchProposal.proposal_date}}
            </td>
          </tr>
        </table>
      </div>
    </li>
  </ul>
</div>

<% content_for :javascript do %>
    <script type="text/javascript">
      $(document).on('ready page:load', function () {
        angular.bootstrap(document, ['matchesAngularApp']);
      });
    </script>
<% end %>

app/views/matches/new.html.erb
<h1>Add a match</h1>
<%= render "form" %>

app/views/matches/show.html.erb
<%= link_to 'Edit match', edit_match_path(@match), class: [:button, 'float_right'] %>
<h1>Match</h1>

<% if @match_proposal %>
    <p>This match accepted from a <%= link_to 'match proposal', @match_proposal %> created
      on <%= @match_proposal.created_at.strftime('%F') %></p>
<% end %>

<table class="meta_table">
  <tr>
    <th>Client</th>
    <td>
      <%= link_to @match.client_name, client_path(@match.client_id) %>
    </td>
  </tr>
  <tr>
    <th>Volunteer</th>
    <td>
      <%= link_to @match.volunteer_name, volunteer_path(@match.volunteer_id) %>
    </td>
  </tr>
  <tr>
    <th>Day and time</th>
    <td>
      <%= @match.day_and_time %>
    </td>
  </tr>
  <tr>
    <th>Date created</th>
    <td>
      <%= formatted_created_at(@match) %>
    </td>
  </tr>
</table>