config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'static_pages#home'

  resources :clients do
    resources :matches, only: [:show, :index]
  end

  resources :volunteers do
    resources :matches, only: [:show, :index]
    member do
      post 'add_availabilities'
      patch 'add_specialty'
      get 'remove_specialty'
    end
  end

  get 'matches/explorer' => 'matches#explorer', as: :matches_explorer
  resources :match_explorations, only: 'create'
  resources :matches
  resources :match_requests, only: [:update]
  resources :match_proposals do
    resources :match_requests
  end
  resources :availabilities
  resources :specialties
end

app/views/refills/_accordion_tabs.html.erb
<ul class="accordion-tabs">
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="is-active tab-link">Tab Item</a>
    <div class="tab-content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt pellentesque lorem, id suscipit dolor rutrum id. Morbi facilisis porta volutpat. Fusce adipiscing, mauris quis congue tincidunt, sapien purus suscipit odio, quis dictum odio tortor in sem. Ut sit amet libero nec orci mattis fringilla. Praesent eu ipsum in sapien tincidunt molestie sed ut magna. Nam accumsan dui at orci rhoncus pharetra tincidunt elit ullamcorper. Sed ac mauris ipsum. Nullam imperdiet sapien id purus pretium id aliquam mi ullamcorper.</p>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="tab-link">Another Tab</a>
    <div class="tab-content">
      <p>Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices. Pellentesque ac sapien ac purus gravida ullamcorper. Duis rhoncus sodales lacus, vitae adipiscing tellus pharetra sed. Praesent bibendum lacus quis metus condimentum ac accumsan orci vulputate. Aenean fringilla massa vitae metus facilisis congue. Morbi placerat eros ac sapien semper pulvinar. Vestibulum facilisis, ligula a molestie venenatis, metus justo ullamcorper ipsum, congue aliquet dolor tortor eu neque. Sed imperdiet, nibh ut vestibulum tempor, nibh dui volutpat lacus, vel gravida magna justo sit amet quam. Quisque tincidunt ligula at nisl imperdiet sagittis. Morbi rutrum tempor arcu, non ultrices sem semper a. Aliquam quis sem mi.</p>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="tab-link">Third</a>
    <div class="tab-content">
      <p>Donec mattis mauris gravida metus laoreet non rutrum sem viverra. Aenean nibh libero, viverra vel vestibulum in, porttitor ut sapien. Phasellus tempor lorem id justo ornare tincidunt. Nulla faucibus, purus eu placerat fermentum, velit mi iaculis nunc, bibendum tincidunt ipsum justo eu mauris. Nulla facilisi. Vestibulum vel lectus ac purus tempus suscipit nec sit amet eros. Nullam fringilla, enim eu lobortis dapibus, quam magna tincidunt nibh, sit amet imperdiet dolor justo congue turpis.</p>    
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="javascript:void(0)" class="tab-link">Last Item</a>
    <div class="tab-content">
      <p>Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus dui urna.</p>
    </div>
  </li>
</ul>

app/views/refills/_badges.html.erb
<div>
  <span class="badge">4</span>
  <span class="badge-alert">4</span>
  <span class="badge-error">4</span>
  <span class="badge-notice">4</span>
  <span class="badge-success">4</span>
</div>

app/views/refills/_breadcrumbs.html.erb
<div class="breadcrumb">
  <a href="javascript:void(0)">One</a>
  <a href="javascript:void(0)">Two</a>
  <a href="javascript:void(0)">Three</a>
  <a href="javascript:void(0)">Four</a>
  <a href="javascript:void(0)">Five</a>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="/" class="logo">
      <%= image_tag("logo.png") %>
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><a href="<%= clients_path %>">Clients</a></li>
        <li class="nav-link"><a href="<%= volunteers_path %>">Volunteers</a></li>
        <li class="nav-link"><a href="<%= specialties_path %>">Specialties</a></li>
        <li class="nav-link"><a href="<%= matches_path %>">Matches</a></li>
        <li class="nav-link"><a href="<%= matches_explorer_path %>">Match Explorer</a></li>
      </ul>
    </nav>
  </div>
</header>